apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-pv
  labels:
    volume: post
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    shareName: post-pv
    secretName: post-secret
    readOnly: false