apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadOnlyMany
  selector:
    matchLabels:
      volume: post
  storageClassName: ""