apiVersion: v1
kind: Secret
metadata:
  name: post-secret
data:
  azurestorageaccountname: bWhzb25nc3RvcmFnZQ==
  azurestorageaccountkey: VkRRZitXVHhrZzF1aXpROE91Q2JhL3hzcHZkWlFpQWR6a0IwenNXYW5ONHk3T2JMekVITHc4NEMwandZNEpjTVViemt0c0djRk5hTUUyY25pNGVjTHc9PQ==